import './globals.css'
import { Inter } from 'next/font/google'
import Link from 'next/link'
import LoginBtn from './LoginBtn'
import { getServerSession } from 'next-auth'
import { authOptions } from '@/pages/api/auth/[...nextauth]'

const inter = Inter({ subsets: ['latin'] })

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default async function RootLayout({ children }) {
  // 로그인된 정보 가져오기
  let session = await getServerSession(authOptions)
  console.log(session)
  
  return (
    <html lang="en">
      <body className={inter.className}>
        <div>
          <div className='navbar'>
            <Link href="/">Home</Link>
            <Link href="/list">List</Link>
            <Link href="/write">Write</Link>
            <LoginBtn/>
          </div>
        </div>
      {children} {/*page.js 가 여기 들어감*/}
      </body>
    </html>
  )
}
